title: ShuwaShuwaBlog
author: Shou
email: nmmarzano@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog!!
# social links
github_username: nmmarzano

show_excerpts: true # set to false to remove excerpts on the homepage


theme: minima
